name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
        
        - name: Install dependencies 
          run: |
            make install
        - name: run the code
          run : |
            make run
        - name: Run tests
          run: pytest test.py